name: Build lxc for Android arm64

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
             sudo apt-get update -qq
             sudo apt-get install -qq gcc-aarch64-linux-gnu clang meson llvm
             sudo apt-get install -qq libapparmor-dev libcap-dev libseccomp-dev libselinux1-dev linux-libc-dev libpam0g-dev docbook2x libsystemd-dev

      - name: Get latest lxc version
        run: |
          git clone https://github.com/lxc/lxc.git
          cd lxc
          git fetch --tags
          latest_version=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $latest_tag
          echo "Latest lxc version: $latest_version"

      - name: Get toolchain version
        run: |
          aarch64-linux-gnu-gcc -v

      - name: Build lxc
        run: |
          CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ meson setup -Dprefix=/data/lxc build
          CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ meson compile -C build
          make && make install
          cat ./build/meson-logs/meson-log.txt

      - name: Zip lxc
        run: |
          cd lxc_install
          lxc_version=$(lxc/lxc --version | cut -d" " -f2)
          tar -czvf lxc_$lxc_version.tar.gz *
          mv lxc_$lxc_version.tar.gz ${{ github.workspace }}/lxc_$lxc_version.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lxc
          path: lxc_$lxc_version.tar.gz
