name: Build lxc for Android arm64

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
             sudo apt-get update -qq
             sudo apt-get install --yes \
                  apparmor bash-completion bridge-utils build-essential \
                  busybox-static clang cloud-image-utils curl dbus debhelper debootstrap \
                  devscripts dnsmasq-base docbook2x doxygen ed fakeroot file gcc cmake graphviz \
                  git iptables meson net-tools libapparmor-dev libcap-dev libgnutls28-dev liblua5.2-dev \
                  libpam0g-dev libseccomp-dev libselinux1-dev libtool linux-libc-dev \
                  llvm lsb-release make openssl pkg-config python3-all-dev \
                  python3-setuptools rsync squashfs-tools uidmap unzip uuid-runtime \
                  wget xz-utils systemd-coredump libdbus-1-dev libsystemd-dev
             sudo apt-get remove --yes lxc-utils liblxc-common liblxc1 liblxc-dev

      - name: Get latest lxc version
        run: |
          git clone https://github.com/lxc/lxc.git
          cd lxc
          latest_version=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest lxc version: $latest_version"
          rm -rf ./*
          cd ../
          wget https://github.com/lxc/lxc/archive/refs/tags/$latest_version.tar.gz
          tar -zxvf $latest_version.tar.gz

      - name: Configure the Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
          unzip android-ndk-r26b-linux.zip
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.2.9519653
          export PATH=$PATH:$ANDROID_NDK_HOME
          export PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
          export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/33
          mkdir -p ~/.local/share/meson/cross/
          
          echo "[binaries]" > ~/.local/share/meson/cross/android-aarch64
          echo "c = '$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang'" >> ~/.local/share/meson/cross/android-aarch64
          echo "cpp = '$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++'" >> ~/.local/share/meson/cross/android-aarch64
          echo "ar = '$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar'" >> ~/.local/share/meson/cross/android-aarch64
          echo "ld = '$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/ld'" >> ~/.local/share/meson/cross/android-aarch64
          echo "strip = '$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip'" >> ~/.local/share/meson/cross/android-aarch64
          echo "pkgconfig = '/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'" >> ~/.local/share/meson/cross/android-aarch64
          echo "" >> ~/.local/share/meson/cross/android-aarch64
          
          echo "[properties]" >> ~/.local/share/meson/cross/android-aarch64
          echo "sys_root = '$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot'" >> ~/.local/share/meson/cross/android-aarch64
          echo "" >> ~/.local/share/meson/cross/android-aarch64

          echo "[built-in options]" >> ~/.local/share/meson/cross/android-aarch64
          echo "c_args = ['-O2', '-pipe', '-g', '-feliminate-unused-debug-types', '--sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot']" >> ~/.local/share/meson/cross/android-aarch64
          echo "c_link_args = ['-Wl,-O1', '-Wl,--hash-style=gnu', '-Wl,--as-needed']" >> ~/.local/share/meson/cross/android-aarch64
          echo "cpp_args = ['-O2', '-pipe', '-g', '-feliminate-unused-debug-types', '--sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot']" >> ~/.local/share/meson/cross/android-aarch64
          echo "cpp_link_args = ['-Wl,-O1', '-Wl,--hash-style=gnu', '-Wl,--as-needed']" >> ~/.local/share/meson/cross/android-aarch64

      - name: Check the compilation configuration
        run: |
          echo C Path:
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang --version
          echo PKG-CONFIG Path:
          pkg-config --list-all
          pkg-config --variable pc_path pkg-config
          echo ENV:
          env
        
      - name: Build lxc
        run: |
          version=$(ls | grep -oP '(?<=lxc-lxc-)[\d.]+')
          cd lxc-lxc-$version
          ls -al /usr/local/share/pkgconfig
          ls -al /usr/lib/x86_64-linux-gnu/pkgconfig
          ls -al /usr/lib/pkgconfig:/usr/share/pkgconfig
          meson setup build --cross-file android-aarch64
          meson compile -C build --cross-file android-aarch64
          #make && make install

      - name: Zip lxc
        run: |
          cd lxc_install
          lxc_version=$(lxc/lxc --version | cut -d" " -f2)
          tar -czvf lxc_$lxc_version.tar.gz *
          mv lxc_$lxc_version.tar.gz ${{ github.workspace }}/lxc_$lxc_version.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lxc
          path: lxc_$lxc_version.tar.gz
