name: Build lxc for Android arm64

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
             sudo apt-get update && sudo apt-get install --yes --no-install-recommends \
             build-essential automake autoconf libtool libcap-dev libapparmor-dev git python3-pip \
             libdbus-1-dev
             pip3 install meson==0.63

      - name: Get latest lxc version
        run: |
          rm -rf lxc
          git clone https://github.com/lxc/lxc.git
          cd lxc
          latest_version=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest lxc version: $latest_version"

      - name: Download and setup arm64-linux-android toolchain
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip
          export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e
          export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          $ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch arm64 --api 29 --install-dir $(pwd)/lxc/arm64-linux-android-toolchain >/dev/null 2>&1
          export PATH=$PATH:$(pwd)/lxc/arm64-linux-android-toolchain/bin
          ls $(pwd)/lxc/arm64-linux-android-toolchain/bin/

      - name: Build lxc
        run: |
          cd lxc
          git checkout $latest_version
          CC=$(pwd)/arm64-linux-android-toolchain/bin/aarch64-linux-android-gcc CXX=$(pwd)/arm64-linux-android-toolchain/bin/aarch64-linux-android-g++ meson setup -Dprefix=/data/lxc build
          CC=$(pwd)/arm64-linux-android-toolchain/bin/aarch64-linux-android-gcc CXX=$(pwd)/arm64-linux-android-toolchain/bin/aarch64-linux-android-g++ meson compile -C build
          make && make install

      - name: Zip lxc
        run: |
          cd lxc_install
          lxc_version=$(lxc/lxc --version | cut -d" " -f2)
          tar -czvf lxc_$lxc_version.tar.gz *
          mv lxc_$lxc_version.tar.gz ${{ github.workspace }}/lxc_$lxc_version.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lxc
          path: lxc_$lxc_version.tar.gz
